# Generated by Django 4.1.2 on 2022-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-03-22'),
            preserve_default=False,
        ),
    ]
